version: '2'

volumes:
  db-volume:

services:

  # DB container
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db-volume:/var/lib/mysql

  # Container to run cli applications (composer, drush, etc.)
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile-php-cli
      args:
        USER_UID: ${USER_UID}
    volumes:
      # Data of application
      - .:/var/www/html:rw
      # Share the local user's composer cache and settings
      - ~/.composer:/home/php/.composer:rw
      # Share the local user's npm cache as a Docker volume
      - ~/.npm:/home/php/.npm:rw
      # Share the local user's SSH keys and configuration (read-only)
      - ~/.ssh:/home/php/.ssh:ro
      - ~/.ssh/known_hosts:/home/php/.ssh/known_hosts:rw
      - ~/.gitconfig:/home/php/.gitconfig
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    links:
      - db

  # php-fpm container used as PHP runtime for the web server
  php-fpm:
    image: drupaldocker/php-dev:7.0-fpm
    volumes:
      - .:/var/www/html:rw
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    links:
      - db

  # The web server used to access the developement website
  web:
    image: drupaldocker/nginx
    environment:
      DOCROOT: /var/www/html/web
    ports:
      - ${PORT}:80
    volumes:
      - .:/var/www/html:rw
    links:
      - php-fpm:php
